const names = require("./04-names.js");
const sayHi = require("./05-utils.js");
const data = require("./06-alternative-flavor.js");
require("./07-mind-grenade.js");
console.log(names.john);
console.log(names.peter);
console.log(names);
sayHi("Kevin");
console.log(data.id);
console.log(data.flavor);
